logging.level:
  root: INFO
  org.springframework.web: INFO
  org.hibernate: ERROR

spring:
  mustache:
    suffix: .mst
    prefix: /WEB-INF/templates/
  mvc:
    contentnegotiation:
      favor-path-extension: true
    static-path-pattern: /public/**
  resources.static-locations:
    - "classpath:/public"
  devtools:
    restart:
      exclude: public/**
      enabled: true


ds:
  driverClass: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:7788/zentao?useUnicode=true&useSSL=false&characterEncoding=utf-8&useSSL=false
  user: zentao
  password: zentao1024
  minPoolSize: 3
  initialPoolSize: 3
  maxPoolSize: 10
  maxIdleTime: 600
  acquireIncrement: 10
  acquireRetryAttempts: 10
  checkoutTimeout: 10000


mybatis:
  map-underscore-to-camel-case: true
  logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl

app:
  task-status:
    - done
    - closed
