logging.level:
  root: INFO
  org.springframework.web: INFO
  org.hibernate: ERROR
  org.zentao.mapper: debug


spring:
  mustache:
    suffix: .mst
  mvc:
    contentnegotiation:
      favor-path-extension: true
    static-path-pattern: /public/**
  resources.static-locations:
    - "classpath:/public"
  devtools:
    restart:
      exclude:
          - "classpath:/public/**"
          - "classpath:/templates/**"
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/zentao?useUnicode=true&useSSL=false&characterEncoding=utf-8&useSSL=false
    hikari:
      idleTimeout: 300000
      connectionTimeout: 10000
      username: root
      password: 123456
      maximumPoolSize: 5

mybatis:
  map-underscore-to-camel-case: true
  logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl

app:
  task-status:
    - done
    - closed
  story-status:
    - closed

thread:
  query-pool:
    max-size: 500
    core-size: 10
    keep-alive-sec: 60
    backqueue-size: 100


server:
  compression:
    enabled: true
  jetty:
    acceptors: 10
  port: 8888
