logging.level:
  root: INFO
  org.springframework.web: INFO
  org.hibernate: ERROR

spring:
  mustache:
    suffix: .mst
  mvc:
    contentnegotiation:
      favor-path-extension: true
    static-path-pattern: /public/**
  resources.static-locations:
    - "classpath:/public"
  devtools:
    restart:
      exclude:
          - "classpath:/public/**"
          - "classpath:/templates/**"
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:7788/zentao?useUnicode=true&useSSL=false&characterEncoding=utf-8&useSSL=false
    hikari:
      idleTimeout: 300000
      connectionTimeout: 10000
      username: zentao
      password: zentao1024
      maximumPoolSize: 5

mybatis:
  map-underscore-to-camel-case: true
  logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl

app:
  task-status:
    - done
    - closed
  story-status:
    - closed

thread:
  query-pool:
    max-size: 500
    core-size: 10
    keep-alive-sec: 60
    backqueue-size: 100


